Repository oliverdn95/soulpet-back, pull requests merged in 2023-05, with the labels that each got.

#36 Concluído Task BE-10 recurso GET para listagem de serviços
  index.js
  routes/servicos.js
Labels: documentation, enhancement

#37 Concluido Task BE-11 Rota Post para Serviços
  index.js
  routes/servicos.js
Labels: documentation, enhancement

#38 Concluído Task BE-15 - criação da rota POST para agendamentos
  index.js
  routes/agendamentos.js
Labels: documentation, enhancement

#40 CONCLUIDO TASK BE-12 CRIAR RECURSO PUT PARA ATULIZAÇÃO DE SERVIÇOS
  routes/servicos.js
Labels: documentation, enhancement

#41 CONCLUIDO TASK BE-13 CRIAR RECURSO DELETE PARA REMOÇÃO DE SERVIÇOS
  routes/servicos.js
Labels: documentation, enhancement

#42 Concluída Task BE-14 rota GET para Agendamentos
  routes/agendamentos.js
  routes/servicos.js
Labels: documentation, enhancement

#43 CONCLUIDO TASK BE-17 CRIAR RECURSO DELETE PARA REMOÇÃO DE AGENDAMENTO…
  routes/agendamentos.js
  routes/produtos.js
  routes/servicos.js
Labels: documentation, enhancement

#44 Refatoração da task BE-5 delete para remoção de produtos
  routes/produtos.js
Labels: enhancement

#45 Concluída Task BE-20 Criando a rota Post para Pedidos
  database/pedido.js
  database/produto.js
  index.js
  routes/pedidos.js
Labels: documentation, enhancement

#46 Concluído Task BE-19 Criar recurso Get para Pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#47 Melhoria na verificação de existência de produtos, quantidades e clie…
  routes/pedidos.js
Labels: enhancement

#48 Concluido Task BE-21 Criar PUT para atualização de Pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#51 Concluido task SPT-12 Melhorias de segurança e desempenho do Backend
  .env.example
  index.js
  package-lock.json
  package.json
  routes/healthchecker.js
Labels: enhancement

#52 Concluído Task BE-22 rota deletar pedidos
  routes/pedidos.js
Labels: documentation, enhancement

#53 CORREÇÃO TASK BE-12
  database/agendamento.js
  database/produto.js
  routes/servicos.js
Labels: documentation, enhancement

#54 Concluido Task SPT-7 Criar README.md e LICENCE.md Back-End
  LICENCE.md
  README.md
  database/produto.js
Labels: documentation, enhancement

#56 Alterando o nome de Licence para License
  LICENSE.md
Labels: documentation
